### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by josephtarbit** [GregTech-Intergalactical/GregTech#116]
```
java.lang.IllegalStateException: Call to GraphWrapper::getController on client side!
	at tesseract.api.GraphWrapper.getController(GraphWrapper.java:92) ~[TesseractAPI-1.18.1-0.1.jar%2360!:1.18.1-0.1] {re:classloading}
	at muramasa.antimatter.pipe.BlockCable.m_7892_(BlockCable.java:88) ~[AntimatterAPI-1.18.1-0.1.jar%2352!:1.18.1-0.1] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60682_(BlockBehaviour.java:683) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.Entity.m_20101_(Entity.java:891) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_146872_(Entity.java:686) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:658) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.client.player.LocalPlayer.m_6478_(LocalPlayer.java:848) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:runtimedistcleaner:A,re:mixin,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:mixin:APP:create.mixins.json:HeavyBootsOnPlayerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.entity.LivingEntity.m_21074_(LivingEntity.java:2145) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntity.java:2102) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_7023_(Player.java:1390) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2534) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:491) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.client.player.LocalPlayer.m_8107_(LocalPlayer.java:764) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:runtimedistcleaner:A,re:mixin,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:mixin:APP:create.mixins.json:HeavyBootsOnPlayerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2243) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:188) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:computing_frames,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:runtimedistcleaner:A,re:mixin,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientplayerentity_respawnplayer,pl:mixin:APP:create.mixins.json:HeavyBootsOnPlayerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:222) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:antimatter.mixins.json:ClientBlockUpdateMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:antimatter.mixins.json:ClientBlockUpdateMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:antimatter.mixins.json:ClientBlockUpdateMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1674) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2362!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.0.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}```

**Comment by Vliro** [comment]
Forgot a client side check simply

**Comment by Vliro** [comment]
I think the issue is with collision. Don't collide with cables for now!

**Comment by Vliro** [comment]
fixed
