### ISSUE TITLE
无法启动服务器

### ISSUE THREAD

**Issue by Tentou-Reikie** [GregTech-Intergalactical/GregTech#123]
抱歉，我不太懂Github上的礼仪。
当我尝试运行run.bat，使用Forge-1.18.1-39.0.64服务器启动本模组时。产生了如下的报告：
`
D:\GTI_Server>REM Forge requires a configured set of both JVM and program arguments.

D:\GTI_Server>REM Add custom JVM arguments to the user_jvm_args.txt

D:\GTI_Server>REM Add custom program arguments {such as nogui} to this file in the next line before the  or

D:\GTI_Server>REM  pass them to this script directly

D:\GTI_Server>".\jdk-17.0.2\bin\java.exe" @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.1-39.0.64/win_args.txt nogui
[11:04:21] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.0.64, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, nogui]
[11:04:21] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.2 by Oracle Corporation
[11:04:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/GTI_Server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=SERVER
[11:04:21] [main/INFO]: Found mod file AntimatterAPI-1.18.1-0.1.jar of type MOD with locator {mods folder locator at D:\GTI_Server\mods}
[11:04:21] [main/INFO]: Found mod file GregTech-Intergalactical-1.18.1-0.1.jar of type MOD with locator {mods folder locator at D:\GTI_Server\mods}
[11:04:21] [main/INFO]: Found mod file TesseractAPI-1.18.1-0.1.jar of type MOD with locator {mods folder locator at D:\GTI_Server\mods}
[11:04:21] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.64.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654d8173
[11:04:21] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.64.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654d8173
[11:04:21] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.64.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654d8173
[11:04:21] [main/INFO]: Found mod file server-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654d8173
[11:04:21] [main/INFO]: Found mod file forge-1.18.1-39.0.64-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654d8173
[11:04:23] [main/INFO]: Compatibility level set to JAVA_17
[11:04:23] [main/INFO]: Launching target 'forgeserver' with arguments [nogui]
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[11:04:28] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.64, for MC 1.18.1 with MCP 20211210.034407
[11:04:28] [modloading-worker-0/INFO]: MinecraftForge v39.0.64 Initialized
[11:04:28] [modloading-worker-0/INFO]: Loading Antimatter
[11:04:28] [modloading-worker-0/INFO]: Loading GregTech
[11:04:28] [main/INFO]: Registration event DATA_INIT
[11:04:31] [main/WARN]: Registry minecraft:block_entity_type: The object net.minecraft.world.level.block.entity.BlockEntityType@20df4560 has been registered twice for the same name antimatter:proxy.
[11:04:32] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/placed_feature / antimatter:stone_layer]' to registry
[11:04:32] [modloading-worker-0/INFO]: AntimatterAPI WorldGen Initialization Stage...
[11:04:32] [modloading-worker-0/INFO]: Registration event WORLDGEN_INIT
[11:04:32] [modloading-worker-0/INFO]: AntimatterAPI Data Processing has Finished. All Data Objects can now be Modified!
[11:04:32] [modloading-worker-0/INFO]: Registration event DATA_READY
[11:04:32] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[11:04:33] [Forge Version Check/INFO]: [forge] Found status: BETA_OUTDATED Current: 39.0.64 Target: 39.0.66
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.64/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/chunk/RenderChunkRegion
        at TRANSFORMER/gregtech@1.18.1-0.1/muramasa.gregtech.block.BlockTurbineCasing.getWorld(BlockTurbineCasing.java:170)
        at TRANSFORMER/gregtech@1.18.1-0.1/muramasa.gregtech.block.BlockTurbineCasing.getTurbine(BlockTurbineCasing.java:181)
        at TRANSFORMER/gregtech@1.18.1-0.1/muramasa.gregtech.block.BlockTurbineCasing.getConfig(BlockTurbineCasing.java:61)
        at TRANSFORMER/antimatter@1.18.1-0.1/muramasa.antimatter.dynamic.BlockDynamic.m_5940_(BlockDynamic.java:68)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60651_(BlockBehaviour.java:587)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60808_(BlockBehaviour.java:583)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour.m_7952_(BlockBehaviour.java:258)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60768_(BlockBehaviour.java:482)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60804_(BlockBehaviour.java:570)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase$Cache.<init>(BlockBehaviour.java:813)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java:452)
        at TRANSFORMER/forge@39.0.64/net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:506)
        at TRANSFORMER/forge@39.0.64/net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:526)
        at TRANSFORMER/forge@39.0.64/net.minecraftforge.registries.GameData.lambda$freezeData$5(GameData.java:290)
        at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572)
        at TRANSFORMER/forge@39.0.64/net.minecraftforge.registries.GameData.freezeData(GameData.java:288)
        at TRANSFORMER/forge@39.0.64/net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:46)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.64/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:199)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.64/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:199)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.64/net.minecraftforge.fml.ModLoader.lambda$finishMods$17(ModLoader.java:189)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.64/net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:189)
        at TRANSFORMER/forge@39.0.64/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:48)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.Main.main(Main.java:104)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.chunk.RenderChunkRegion
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)`

**Comment by ProsperCraft** [comment]
What happens if you use a modern forge for 1.18.2?

We have it running on 1.18.2

**Comment by Tentou-Reikie** [comment]
> What happens if you use a modern forge for 1.18.2?
> 
> We have it running on 1.18.2

谢谢！在1.18.2上能正常开启服务器了！
Thanks! The server can be started normally on 1.18.2! ——By Google Translate

**Comment by ProsperCraft** [comment]
Fantastic! Don't forget to close the issue.
