### ISSUE TITLE
Exception message: java.lang.NoSuchMethodError: muramasa.antimatter.AntimatterAPI.getRecipeRegistrate()Lmuramasa/antimatter/recipe/loader/IRecipeRegistrate;

### ISSUE THREAD

**Issue by DeprisAlexis** [GregTech-Intergalactical/GregTech#126]
Stacktrace:
	at muramasa.gti.GregTech.registerRecipeLoaders(GregTech.java:64) ~[?:1.16.5-0.0.5] {re:classloading}
	at muramasa.gti.GregTech.<init>(GregTech.java:60) ~[?:1.16.5-0.0.5] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3165/1533639059.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3789/578703016.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by ProsperCraft** [comment]
Did you add the required Animatter library mod?

**Comment by yuanweilihuabai** [comment]
I ran into the same problem, my GTI version is 0.0.5, antimatterAPI version is 0.1.1, and TesseractAPI version is 0.1

**Comment by Trinsdar** [comment]
duplicate
