### ISSUE TITLE
GTI 0.0.5 crashes on 1.16.5 Forge v36.2.39

### ISSUE THREAD

**Issue by Skrrby** [GregTech-Intergalactical/GregTech#131]
[20:12:46] [modloading-worker-4/ERROR]: Failed to create mod instance. ModID: gti, class muramasa.gti.GregTech
java.lang.NoSuchMethodError: muramasa.antimatter.AntimatterAPI.getRecipeRegistrate()Lmuramasa/antimatter/recipe/loader/IRecipeRegistrate;
	at muramasa.gti.GregTech.registerRecipeLoaders(GregTech.java:64) ~[?:1.16.5-0.0.5]
	at muramasa.gti.GregTech.<init>(GregTech.java:60) ~[?:1.16.5-0.0.5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) [?:36.2]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3112/297795507.run(Unknown Source) [?:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3567/227843012.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]

**Comment by Trinsdar** [comment]
duplicate
