### ISSUE TITLE
Crash when putting fluid cell into coal boiler

### ISSUE THREAD

**Issue by lynxx131** [GregTech-Intergalactical/GregTech#140]
So if you put a cell into the top left slot of the coal boiler the game crashes with this error, it doesn't matter if there's steam or water inside or not.

```
java.lang.NoSuchMethodError: 'net.minecraftforge.fluids.FluidStack net.minecraftforge.fluids.FluidUtil.tryFluidTransfer(net.minecraftforge.fluids.capability.IFluidHandler, net.minecraftforge.fluids.capability.IFluidHandler, long, boolean)'
	at muramasa.gregtech.tile.single.TileEntityCoalBoiler$CoalBoilerFluidHandler.lambda$fillCell$2(TileEntityCoalBoiler.java:304) ~[gregtech-forge-1.18.2-0.1.jar%2354!/:1.18.2-0.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.18.2-40.1.85-universal.jar%2363!/:?] {re:classloading}
	at muramasa.gregtech.tile.single.TileEntityCoalBoiler$CoalBoilerFluidHandler.lambda$fillCell$3(TileEntityCoalBoiler.java:302) ~[gregtech-forge-1.18.2-0.1.jar%2354!/:1.18.2-0.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.1.85-universal.jar%2363!/:?] {re:classloading}
	at muramasa.gregtech.tile.single.TileEntityCoalBoiler$CoalBoilerFluidHandler.lambda$fillCell$4(TileEntityCoalBoiler.java:301) ~[gregtech-forge-1.18.2-0.1.jar%2354!/:1.18.2-0.1] {re:classloading}
	at muramasa.antimatter.capability.Holder.ifPresent(Holder.java:120) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading}
	at muramasa.gregtech.tile.single.TileEntityCoalBoiler$CoalBoilerFluidHandler.fillCell(TileEntityCoalBoiler.java:295) ~[gregtech-forge-1.18.2-0.1.jar%2354!/:1.18.2-0.1] {re:classloading}
	at muramasa.antimatter.capability.machine.MachineFluidHandler.tryFillCell(MachineFluidHandler.java:132) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading}
	at muramasa.antimatter.capability.machine.MachineFluidHandler.onMachineEvent(MachineFluidHandler.java:148) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading}
	at muramasa.antimatter.tile.TileEntityMachine.lambda$onMachineEvent$13(TileEntityMachine.java:281) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading,re:mixin}
	at muramasa.antimatter.capability.Holder.ifPresent(Holder.java:120) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading}
	at muramasa.antimatter.tile.TileEntityMachine.onMachineEvent(TileEntityMachine.java:281) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading,re:mixin}
	at muramasa.antimatter.capability.item.TrackedItemHandler.onContentsChanged(TrackedItemHandler.java:45) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading}
	at muramasa.antimatter.capability.item.ItemStackHandler.setStackInSlot(ItemStackHandler.java:36) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading}
	at net.minecraftforge.items.SlotItemHandler.m_5852_(SlotItemHandler.java:47) ~[forge-1.18.2-40.1.85-universal.jar%2363!/:?] {re:classloading}
	at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:161) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:410) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:295) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,re:mixin}
	at muramasa.antimatter.gui.container.AntimatterContainer.m_150399_(AntimatterContainer.java:94) ~[AntimatterAPI-forge-1.18.2-0.2-pre6.jar%2353!/:1.18.2-0.2-pre6] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1309) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

Screenshot:

https://i.imgur.com/IZS7XIc.jpg

This is with the most recent builds of Antimatter, Tesseract and GTI.

crash report https://pastebin.com/CTS417Ei

**Comment by lynxx131** [comment]
Bit more info:

Crash only happens if you place an empty fluid container like a cell or a bucket into the boiler as per my screenshot.

If I put a bucket of water into the slot then nothing happens.

**Comment by Vliro** [comment]
@Trinsdar this is about multi loader right
