### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Water-Gate-King** [GregTech-Intergalactical/GregTech#187]
### What happened?

The game crash when it startup. I can not enter the game .

### What mod loaders are you seeing the problem on?

Forge

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023/6/28 上午8:44
Description: Rendering overlay

net.minecraftforge.fml.ModLoadingException: AntimatterAPI (antimatter) encountered an error during the sided_setup event phase
§7java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableMap.getOrDefault(Object, Object)" because "muramasa.gregtech.data.TierMaps.TIER_CIRCUITS" is null
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:110) ~[javafmllanguage-1.18.2-40.2.4.jar%2360!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.4.jar%2359!/:?] {re:mixin}
	at java.util.HashMap.forEach(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.2.4.jar%2359!/:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.4.jar%2359!/:?] {re:mixin}
	at net.minecraft.server.packs.repository.FolderRepositorySource.handler$zza000$register(FolderRepositorySource.java:535) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,re:classloading,pl:mixin:APP:arrp.mixins.json:FileResourcePackProviderMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.FolderRepositorySource.m_7686_(FolderRepositorySource.java) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,re:classloading,pl:mixin:APP:arrp.mixins.json:FileResourcePackProviderMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:48) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:40) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_168019_(Minecraft.java:808) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91241_(Minecraft.java:638) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91239_(Minecraft.java:624) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:395) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:551) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:137) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.4.jar%2352!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableMap.getOrDefault(Object, Object)" because "muramasa.gregtech.data.TierMaps.TIER_CIRCUITS" is null
	at muramasa.gregtech.loader.crafting.Machines.lambda$loadRecipes$63(Machines.java:70) ~[gti-forge-0.2-alpha-25-1.18.2.jar%2356!/:0.2-alpha-25-1.18.2] {re:classloading}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?] {}
	at muramasa.gregtech.loader.crafting.Machines.loadRecipes(Machines.java:51) ~[gti-forge-0.2-alpha-25-1.18.2.jar%2356!/:0.2-alpha-25-1.18.2] {re:classloading}
	at muramasa.antimatter.datagen.AntimatterDynamics.collectRecipes(AntimatterDynamics.java:164) ~[AntimatterAPI-forge-0.2-rc18-1.18.2.jar%2355!/:0.2-rc18-1.18.2] {re:classloading,re:mixin}
	at muramasa.antimatter.datagen.AntimatterDynamics.onResourceReload(AntimatterDynamics.java:234) ~[AntimatterAPI-forge-0.2-rc18-1.18.2.jar%2355!/:0.2-rc18-1.18.2] {re:classloading,re:mixin}
	at muramasa.antimatter.datagen.AntimatterDynamics.addDataPacks(AntimatterDynamics.java:104) ~[AntimatterAPI-forge-0.2-rc18-1.18.2.jar%2355!/:0.2-rc18-1.18.2] {re:classloading,re:mixin}
	at muramasa.antimatter.common.event.forge.ModCommonEvents.onResourcePackBeforeUser(ModCommonEvents.java:37) ~[AntimatterAPI-forge-0.2-rc18-1.18.2.jar%2355!/:0.2-rc18-1.18.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_37_ModCommonEvents_onResourcePackBeforeUser_BeforeUser.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.4.jar%2360!/:?] {}
	... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:110) ~[javafmllanguage-1.18.2-40.2.4.jar%2360!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.4.jar%2359!/:?] {re:mixin}
	at java.util.HashMap.forEach(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.2.4.jar%2359!/:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.4.jar%2359!/:?] {re:mixin}
	at net.minecraft.server.packs.repository.FolderRepositorySource.handler$zza000$register(FolderRepositorySource.java:535) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,re:classloading,pl:mixin:APP:arrp.mixins.json:FileResourcePackProviderMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.FolderRepositorySource.m_7686_(FolderRepositorySource.java) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,re:classloading,pl:mixin:APP:arrp.mixins.json:FileResourcePackProviderMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:48) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:40) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_168019_(Minecraft.java:808) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91241_(Minecraft.java:638) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91239_(Minecraft.java:624) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:395) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:551) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:137) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.4.jar%2352!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Mod Resources, Minecraft-Mod-Language-Modpack-1-18.zip
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: all the creatures:sounds.json
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: all the creatures:sounds.json
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:35)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.sounds.SoundManager.m_5944_(SoundManager.java:64)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.sounds.SoundManager.m_5944_(SoundManager.java:39)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11)
	... 7 more

Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2271) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.4.jar%2352!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3.1, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), BellSoft
	Memory: 5970908968 bytes (5694 MiB) / 6723469312 bytes (6412 MiB) up to 6979321856 bytes (6656 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 17 Stepping 0
	Microarchitecture: Zen
	Frequency (GHz): 2.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x15dd
	Graphics card #0 versionInfo: DriverVersion=31.0.12027.9001
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18333.58
	Virtual memory used (MB): 12956.05
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 1136.61
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx6656m
	Launched Version: 1.18.2-Forge
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 3.2.0 Core Profile Context 22.20.27.09.230330, ATI Technologies Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		networkapi-forge-0.1.1-rc2.jar                    |Network API                   |networkapi                    |0.1.1-rc2           |SIDED_SETU|Manifest: NOSIGNATURE
		ARRP-forge-0.6.7-1.18.2.jar                       |Runtime Resource Pack Forge   |arrp                          |0.6.7               |SIDED_SETU|Manifest: NOSIGNATURE
		fluidhandler-extras-1.0.1.jar                     |Fluid Handler long Support    |fluidhandler_extras           |1.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.18.2-40.2.4-universal.jar                 |Forge                         |forge                         |40.2.4              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		TesseractAPI-forge-0.2.1-rc3-1.18.2.jar           |TesseractAPI                  |tesseractapi                  |0.2.1-rc3           |SIDED_SETU|Manifest: NOSIGNATURE
		AntimatterAPI-forge-0.2-rc18-1.18.2.jar           |AntimatterAPI                 |antimatter                    |0.2-rc18            |SIDED_SETU|Manifest: NOSIGNATURE
		gtutility-forge-0.1-pre3-1.18.2.jar               |GT Utility                    |gtutility                     |0.1-pre3            |SIDED_SETU|Manifest: NOSIGNATURE
		botarium-forge-1.18.2-2.0.5-hotfix2.jar           |Botarium                      |botarium                      |2.0.5               |SIDED_SETU|Manifest: NOSIGNATURE
		gti-forge-0.2-alpha-25-1.18.2.jar                 |GregTech Intergalactical      |gti                           |0.2-alpha-25        |SIDED_SETU|Manifest: NOSIGNATURE
		gtrubber-forge-0.2.3-rc2-1.18.2.jar               |GT Rubber                     |gtrubber                      |0.2.3-rc2           |SIDED_SETU|Manifest: NOSIGNATURE
		[JEI物品管理器] jei-1.18.2-9.7.1.255.jar               |Just Enough Items             |jei                           |9.7.1.255           |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: 46aed9b8-7b66-4f81-8302-d382002fcefe
	FML: 40.2
	Forge: net.minecraftforge:40.2.4
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [x] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed GregTech, Antimatter, and Tesseract are up to date.

- [X] Yes

**Comment by Trinsdar** [comment]
probably been long since fixed
