### ISSUE TITLE
[Bug] 开启“更复杂的化学配方”后生成/加载世界时会弹出数据包加载错误

### ISSUE THREAD

**Issue by Tentou-Reikie** [GregTech-Intergalactical/GregTech#189]
### What happened?

When generating/loading worlds after turning on "MORE_COMPLICATED_CHEMICAL_RECIPES", Failed to load datapacks, Whether it's a server or a client.
——Translate by Bing Translator

### What mod loaders are you seeing the problem on?

Forge

### Relevant log output
Server Log :
```shell
[12:49:31] [main/WARN] [minecraft/Main]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: net.minecraftforge.fml.ModLoadingException: AntimatterAPI (antimatter) encountered an error during the done event phase
§7java.lang.RuntimeException: Material: carbon_dioxide does not have liquid
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?] {re:mixin}
	at net.minecraft.server.Main.main(Main.java:183) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
Caused by: net.minecraftforge.fml.ModLoadingException: AntimatterAPI (antimatter) encountered an error during the done event phase
§7java.lang.RuntimeException: Material: carbon_dioxide does not have liquid
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:110) ~[javafmllanguage-1.18.2-40.2.9.jar%2395!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%2394!/:?] {re:mixin}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.2.9.jar%2394!/:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%2394!/:?] {re:mixin}
	at net.minecraft.server.packs.repository.FolderRepositorySource.handler$zza000$register(FolderRepositorySource.java:535) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,re:classloading,pl:mixin:APP:arrp.mixins.json:FileResourcePackProviderMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.FolderRepositorySource.m_7686_(FolderRepositorySource.java) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,re:classloading,pl:mixin:APP:arrp.mixins.json:FileResourcePackProviderMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:48) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:40) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_129819_(MinecraftServer.java:1348) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.WorldStem.m_206911_(WorldStem.java:35) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,re:mixin,pl:mixin:A}
	... 13 more
Caused by: java.lang.RuntimeException: Material: carbon_dioxide does not have liquid
	at muramasa.antimatter.material.Material.getLiquid(Material.java:256) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2341!/:0.2-rc36-1.18.2] {re:mixin,re:classloading}
	at muramasa.antimatter.material.Material.getLiquid(Material.java:276) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2341!/:0.2-rc36-1.18.2] {re:mixin,re:classloading}
	at muramasa.gregtech.loader.machines.ChemicalReactorLoader.addComplicated(ChemicalReactorLoader.java:228) ~[gti-forge-0.2-alpha-45-1.18.2.jar%2361!/:0.2-alpha-45-1.18.2] {re:classloading}
	at muramasa.gregtech.loader.machines.ChemicalReactorLoader.init(ChemicalReactorLoader.java:23) ~[gti-forge-0.2-alpha-45-1.18.2.jar%2361!/:0.2-alpha-45-1.18.2] {re:classloading}
	at muramasa.antimatter.datagen.AntimatterDynamics.lambda$onResourceReload$14(AntimatterDynamics.java:294) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2341!/:0.2-rc36-1.18.2] {re:mixin,re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:212) ~[fastutil-8.5.6.jar%2331!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1051) ~[fastutil-8.5.6.jar%2331!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:215) ~[fastutil-8.5.6.jar%2331!/:?] {}
	at muramasa.antimatter.datagen.AntimatterDynamics.onResourceReload(AntimatterDynamics.java:292) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2341!/:0.2-rc36-1.18.2] {re:mixin,re:classloading}
	at muramasa.antimatter.datagen.AntimatterDynamics.addDataPacks(AntimatterDynamics.java:104) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2341!/:0.2-rc36-1.18.2] {re:mixin,re:classloading}
	at muramasa.antimatter.common.event.forge.ModCommonEvents.onResourcePackBeforeUser(ModCommonEvents.java:37) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2341!/:0.2-rc36-1.18.2] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_85_ModCommonEvents_onResourcePackBeforeUser_BeforeUser.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.9.jar%2395!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%2394!/:?] {re:mixin}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.2.9.jar%2394!/:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%2394!/:?] {re:mixin}
	at net.minecraft.server.packs.repository.FolderRepositorySource.handler$zza000$register(FolderRepositorySource.java:535) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,re:classloading,pl:mixin:APP:arrp.mixins.json:FileResourcePackProviderMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.FolderRepositorySource.m_7686_(FolderRepositorySource.java) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,re:classloading,pl:mixin:APP:arrp.mixins.json:FileResourcePackProviderMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:48) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:40) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_129819_(MinecraftServer.java:1348) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.WorldStem.m_206911_(WorldStem.java:35) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,re:mixin,pl:mixin:A}
	... 13 more
```
Client Log :
```shell
[12:51:27] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: net.minecraftforge.fml.ModLoadingException: AntimatterAPI（antimatter） encountered an error during the done event phase
§7java.lang.RuntimeException: Material: carbon_dioxide does not have liquid
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.Minecraft.m_205125_(Minecraft.java:2085) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1911) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.Minecraft.m_205185_(Minecraft.java:1879) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100972_(CreateWorldScreen.java:246) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$init$13(CreateWorldScreen.java:195) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2351!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2347!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%2351!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:225) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1071) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: net.minecraftforge.fml.ModLoadingException: AntimatterAPI（antimatter） encountered an error during the done event phase
§7java.lang.RuntimeException: Material: carbon_dioxide does not have liquid
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:110) ~[javafmllanguage-1.18.2-40.2.9.jar%23111!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%23110!/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.2.9.jar%23110!/:?]
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%23110!/:?]
	at net.minecraft.server.packs.repository.FolderRepositorySource.handler$zza000$register(FolderRepositorySource.java:535) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.packs.repository.FolderRepositorySource.m_7686_(FolderRepositorySource.java) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:48) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.MinecraftServer.m_129819_(MinecraftServer.java:1348) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.WorldStem.m_206911_(WorldStem.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.Minecraft.m_205125_(Minecraft.java:2083) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	... 34 more
Caused by: java.lang.RuntimeException: Material: carbon_dioxide does not have liquid
	at muramasa.antimatter.material.Material.getLiquid(Material.java:256) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2358!/:0.2-rc36-1.18.2]
	at muramasa.antimatter.material.Material.getLiquid(Material.java:276) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2358!/:0.2-rc36-1.18.2]
	at muramasa.gregtech.loader.machines.ChemicalReactorLoader.addComplicated(ChemicalReactorLoader.java:228) ~[gti-forge-0.2-alpha-45-1.18.2.jar%2378!/:0.2-alpha-45-1.18.2]
	at muramasa.gregtech.loader.machines.ChemicalReactorLoader.init(ChemicalReactorLoader.java:23) ~[gti-forge-0.2-alpha-45-1.18.2.jar%2378!/:0.2-alpha-45-1.18.2]
	at muramasa.antimatter.datagen.AntimatterDynamics.lambda$onResourceReload$14(AntimatterDynamics.java:294) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2358!/:0.2-rc36-1.18.2]
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:212) ~[fastutil-8.5.6.jar%2344!/:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1051) ~[fastutil-8.5.6.jar%2344!/:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:215) ~[fastutil-8.5.6.jar%2344!/:?]
	at muramasa.antimatter.datagen.AntimatterDynamics.onResourceReload(AntimatterDynamics.java:292) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2358!/:0.2-rc36-1.18.2]
	at muramasa.antimatter.datagen.AntimatterDynamics.addDataPacks(AntimatterDynamics.java:104) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2358!/:0.2-rc36-1.18.2]
	at muramasa.antimatter.common.event.forge.ModCommonEvents.onResourcePackBeforeUser(ModCommonEvents.java:37) ~[AntimatterAPI-forge-0.2-rc36-1.18.2.jar%2358!/:0.2-rc36-1.18.2]
	at net.minecraftforge.eventbus.ASMEventHandler_147_ModCommonEvents_onResourcePackBeforeUser_BeforeUser.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.9.jar%23111!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%23110!/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.2.9.jar%23110!/:?]
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%23110!/:?]
	at net.minecraft.server.packs.repository.FolderRepositorySource.handler$zza000$register(FolderRepositorySource.java:535) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.packs.repository.FolderRepositorySource.m_7686_(FolderRepositorySource.java) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:48) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.MinecraftServer.m_129819_(MinecraftServer.java:1348) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.server.WorldStem.m_206911_(WorldStem.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	at net.minecraft.client.Minecraft.m_205125_(Minecraft.java:2083) ~[client-1.18.2-20220404.173914-srg.jar%23109!/:?]
	... 34 more
```

### Anything else?

When I set "MORE_COMPLICATED_CHEMICAL_RECIPES" to "true", I get an error with the above information

[Gameplay]
	#Enables more complicated chemical recipes. - Default: false
	MORE_COMPLICATED_CHEMICAL_RECIPES = true
	#If true logs to planks and planks to sticks give half of vanilla amounts - Default: false
	HARDER_WOOD = true
	#Enables more complicated circuit recipes added in versions of gt5u after 509.25 - Default: false
	HARDER_CIRCUITS = true

When I set "MORE_COMPLICATED_CHEMICAL_RECIPES" to "false", it works fine

[Gameplay]
	#Enables more complicated chemical recipes. - Default: false
	MORE_COMPLICATED_CHEMICAL_RECIPES = false
	#If true logs to planks and planks to sticks give half of vanilla amounts - Default: false
	HARDER_WOOD = true
	#Enables more complicated circuit recipes added in versions of gt5u after 509.25 - Default: false
	HARDER_CIRCUITS = true

GTI Version : gti-forge-0.2-alpha-45-1.18.2
Antimatter Version : AntimatterAPI-forge-0.2-rc36-1.18.2
Tesseract Verrsion : TesseractAPI-forge-0.2.2-pre1-1.18.2

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed GregTech, Antimatter, and Tesseract are up to date.

- [X] Yes

**Comment by Tentou-Reikie** [comment]
Thanks a lot, it's working now!

GTI Version : gti-forge-0.2-1.18.2
Antimatter Version : AntimatterAPI-forge-0.2-1.18.2
Tesseract Version : TesseractAPI-forge-0.2.2-1.18.2
