### ISSUE TITLE
[Bug] Crash during load

### ISSUE THREAD

**Issue by Sto3IV** [GregTech-Intergalactical/GregTech#197]
### What happened?

Forge latest, but tried different versions.
Minecraft 1.12.2
IC 2 Classic 1.12-1.5.8
GregTech Classic 1.1.7

### What mod loaders are you seeing the problem on?

Forge

### Relevant log output

```shell
Prism Launcher version: 8.0-develop (official)


Launched instance in online mode

authserver.mojang.com resolves to:
    [65.9.55.79, 65.9.55.46, 65.9.55.49, 65.9.55.8]

session.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44]

textures.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44]

api.mojang.com resolves to:
    [13.107.246.44, 13.107.213.44]


Minecraft folder is:
M:/PrismLauncher/MODPACKS/Matter/.minecraft


Java path is:
C:/Program Files/Java/jre-1.8/bin/java.exe


Java is version 1.8.0_381, using 64 (amd64) architecture, from Oracle Corporation.


Failed to resolve server address (this is NOT an error!) _minecraft._tcp.: Non existent domain

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  M:/PrismLauncher/MODPACKS/Matter/natives

Libraries:
  M:/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  M:/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  M:/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  M:/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  M:/PrismLauncher/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  M:/PrismLauncher/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  M:/PrismLauncher/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  M:/PrismLauncher/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  M:/PrismLauncher/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  M:/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  M:/PrismLauncher/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  M:/PrismLauncher/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  M:/PrismLauncher/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  M:/PrismLauncher/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  M:/PrismLauncher/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  M:/PrismLauncher/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  M:/PrismLauncher/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  M:/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  M:/PrismLauncher/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  M:/PrismLauncher/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  M:/PrismLauncher/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  M:/PrismLauncher/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  M:/PrismLauncher/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  M:/PrismLauncher/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  M:/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  M:/PrismLauncher/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  M:/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  M:/PrismLauncher/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  M:/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  M:/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  M:/PrismLauncher/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  M:/PrismLauncher/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-universal.jar
  M:/PrismLauncher/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  M:/PrismLauncher/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  M:/PrismLauncher/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  M:/PrismLauncher/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  M:/PrismLauncher/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  M:/PrismLauncher/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  M:/PrismLauncher/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  M:/PrismLauncher/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  M:/PrismLauncher/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  M:/PrismLauncher/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  M:/PrismLauncher/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  M:/PrismLauncher/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  M:/PrismLauncher/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  M:/PrismLauncher/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  M:/PrismLauncher/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  M:/PrismLauncher/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  M:/PrismLauncher/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  M:/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  M:/PrismLauncher/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  M:/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  M:/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  M:/PrismLauncher/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✘] Advanced+Solar+Panels-4.3.0.jar (disabled)
  [✘] Aroma1997Core-1.12.2-2.0.0.2.b167.jar (disabled)
  [✘] AromaBackup-1.12.2-3.0.0.0.b135.jar (disabled)
  [✘] Batty's+Coordinates+PLUS+Mod+for+Forge-1.12.0_004.jar (disabled)
  [✘] beebetteratbees-1.12.2-2.0.3.jar (disabled)
  [✘] BetterFoliage-MC1.12-2.3.1.jar (disabled)
  [✘] BetterSprinting-1.12.2-v3.0.1.jar (disabled)
  [✘] BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar (disabled)
  [✘] blockdrops-1.12.2-1.4.0.jar (disabled)
  [✘] Blur-1.0.4-14.jar (disabled)
  [✘] buildcraft-all-7.99.24.7.jar (disabled)
  [✘] Cavern_1.12.2-v2.3.1.jar (disabled)
  [✘] ChestTransporter-1.12.2-2.8.8.jar (disabled)
  [✘] CodeChickenLib-1.12.2-3.2.3.358-universal.jar (disabled)
  [✘] colytra-1.12.2-1.2.0.4.jar (disabled)
  [✘] Controlling-3.0.10.jar (disabled)
  [✘] cxlibrary-1.12.1-1.6.1.jar (disabled)
  [✘] DeathLocation-1.12-1.jar (disabled)
  [✘] DefaultOptions_1.12.2-9.2.8.jar (disabled)
  [✘] DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar (disabled)
  [✘] Durability+Show-1.12-5.0.0.jar (disabled)
  [✘] EnchantmentDescriptions-1.12.2-1.1.20.jar (disabled)
  [✘] FamiliarFauna-1.12.2-1.0.11.jar (disabled)
  [✘] forestry_1.12.2-5.8.2.422.jar (disabled)
  [✘] Forgelin-1.8.4.jar (disabled)
  [✘] GalacticraftCore-1.12.2-4.0.2.280.jar (disabled)
  [✘] Galacticraft-Planets-1.12.2-4.0.2.280.jar (disabled)
  [✔] GTClassic-1.1.7
  [✘] Hwyla-1.8.26-B41_1.12.2.jar (disabled)
  [✔] IC2Classic-1.12-1.5.8
  [✘] infinitefluids-1.11-1.2.0.jar (disabled)
  [✘] InventoryTweaks-1.64+dev.151.jar (disabled)
  [✘] ironchest-1.12.2-7.0.72.847.jar (disabled)
  [✘] jei_1.12.2-4.16.1.301.jar (disabled)
  [✘] jepb-1.12-1.2.1.jar (disabled)
  [✘] JEROreIntegration-1.12.2-1.1.0.jar (disabled)
  [✘] JustEnoughResources-1.12.2-0.9.2.60.jar (disabled)
  [✘] logisticspipes-0.10.3.72.jar (disabled)
  [✘] MicdoodleCore-1.12.2-4.0.2.280.jar (disabled)
  [✘] moreoverlays-1.14-mc1.12.2.jar (disabled)
  [✘] morepaintings-paintings-1.12.2-5.0.1.2.jar (disabled)
  [✘] More-Planets-1.12.2-2.1.14-GC261.jar (disabled)
  [✘] naturalnetherportals-1.2.0-mc1.12.x.jar (disabled)
  [✘] OpenEye-1.12.2-0.8.jar (disabled)
  [✘] OptiFine_1.12.2_HD_U_F6_pre1_MOD.jar (disabled)
  [🖿] railcraft (folder)
  [✘] railcraft-12.0.0.jar (disabled)
  [✘] rustic-1.1.6.jar (disabled)
  [✘] rusticbopwoods-1.0.jar (disabled)
  [✘] SteveKunG's-Lib-1.12.2-1.1.9.jar (disabled)
  [✘] torohealth-1.12.2-11.jar (disabled)
  [✘] UndergroundBiomesConstructs-1.12-1.3.8.jar (disabled)

Params:
  --username  --version 1.12.2 --gameDir M:/PrismLauncher/MODPACKS/Matter/.minecraft --assetsDir M:/PrismLauncher/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 1920 x 1080

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx40960m, -Duser.language=en]


Minecraft process ID: 61032


[23:07:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:07:55] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:07:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:07:55] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[23:07:55] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_381, running on Windows 11:amd64:10.0, installed at C:\Program Files\Java\jre-1.8
[23:07:56] [main/INFO] [FML]: Searching M:\PrismLauncher\MODPACKS\Matter\.minecraft\mods for mods
[23:07:56] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:07:56] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:07:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:07:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:07:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:07:57] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:07:57] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:07:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:07:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:07:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:07:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:07:57] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:07:57] [Client thread/INFO] [minecraft/Minecraft]: Setting user: Sto3IV
[23:07:58] [Client thread/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[23:07:58] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[23:08:00] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1167439344 bytes (1113 MB) / 1383596032 bytes (1319 MB) up to 38177603584 bytes (36409 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx40960m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.12.1.231124' Renderer: 'AMD Radeon RX 6950 XT'
[23:08:00] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2860 Initialized
[23:08:00] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[23:08:00] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[23:08:00] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[23:08:00] [Client thread/INFO] [FML]: Searching M:\PrismLauncher\MODPACKS\Matter\.minecraft\mods for mods
[23:08:01] [Client thread/INFO] [FML]: Forge Mod Loader has identified 7 mods to load
[23:08:01] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, gtclassic, ic2, ic2-classic-spmod] at CLIENT
[23:08:01] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, gtclassic, ic2, ic2-classic-spmod] at SERVER
[23:08:01] [Client thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:GregTech Classic, FMLFileResourcePack:IndustrialCraft 2 Classic, FMLFileResourcePack:IC2 Classic Detection Helper, ru_ru lang.zip, DO NOT DISABLE.zip
[23:08:01] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[23:08:01] [Client thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[23:08:01] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[23:08:01] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[23:08:01] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[23:08:01] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[23:08:01] [Client thread/INFO] [ic2]: Loading Plugin: [name=JustEnoughItems, version=1.0]
[23:08:01] [Client thread/INFO] [ic2]: Loading Plugin: [name=Baubles Plugin, version=1.0]
[23:08:01] [Client thread/INFO] [ic2]: Loading Plugin: [name=Immersiveengineering, version=1.0]
[23:08:01] [Client thread/INFO] [ic2]: Loading Plugin: [name=Buildcraft Plugin, version=1.0]
[23:08:01] [Client thread/INFO] [ic2]: Loading Plugin: [name=Forestry, version=1.0]
[23:08:01] [Client thread/INFO] [ic2]: Loading Plugin: [name=Actually Additions, version=1.0]
[23:08:01] [Client thread/INFO] [ic2]: Loading Plugin: [name=The One Probe, version=1.0]
[23:08:01] [Client thread/INFO] [ic2]: Loading Plugin: [name=Teleporter Compat, version=1.0]
[23:08:02] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 75682100 nanos
[23:08:03] [Client thread/INFO] [gtclassic]: Hello from GregTech Classic!
[23:08:03] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: AHEAD Target: null
[23:08:03] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
// There are four lights!

Time: 1/23/24 11:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech Classic (gtclassic)
Caused by: java.lang.NoSuchMethodError: gtclassic.api.block.GTBlockBaseMachine.setUnlocalizedName(Lic2/core/platform/lang/components/base/LocaleComp;)Lnet/minecraft/block/Block;
	at gtclassic.api.block.GTBlockBaseMachine.<init>(GTBlockBaseMachine.java:38)
	at gtclassic.common.block.GTBlockMachine.<init>(GTBlockMachine.java:78)
	at gtclassic.common.block.GTBlockMachine.<init>(GTBlockMachine.java:74)
	at gtclassic.common.GTBlocks.<clinit>(GTBlocks.java:114)
	at gtclassic.GTMod.preInit(GTMod.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 828329232 bytes (789 MB) / 1844969472 bytes (1759 MB) up to 38177603584 bytes (36409 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx40960m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                                  | Signature                                |
	|:----- |:----------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2       | minecraft.jar                           | None                                     |
	| LCH   | mcp               | 9.42         | minecraft.jar                           | None                                     |
	| LCH   | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ic2               | 2.8.1001     | IC2Classic-1.12-1.5.8.jar               | None                                     |
	| LCH   | ic2-classic-spmod | 0.0.0.0      | IC2Classic-1.12-1.5.8.jar               | None                                     |
	| LCE   | gtclassic         | 1.1.7        | GTClassic-1.1.7.jar                     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.12.1.231124' Renderer: 'AMD Radeon RX 6950 XT'
[23:08:03] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# M:\PrismLauncher\MODPACKS\Matter\.minecraft\crash-reports\crash-2024-01-23_23.08.03-client.txt
Process exited with code -1.
Clipboard copy at: 23 Jan 2024 23:09:31 +0300
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed GregTech, Antimatter, and Tesseract are up to date.

- [X] Yes

**Comment by Trinsdar** [comment]
this is a crash for gt classic, not gti
