### ISSUE TITLE
Crash when entering end portral

### ISSUE THREAD

**Issue by Tenshi65535** [GregTech-Intergalactical/GregTech#97]
Greetings to all,

I found that when GTI is loaded, the game crash when entering end portal.

Forge        36.1.16
GTI            0.0.3
Antimater 0.0.3
Tesseract  0.0.3

Crash report will be provided below.

**Comment by Tenshi65535** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 5/13/21 3:09 PM
Description: Checking entity block collision

java.lang.NegativeArraySizeException: null
	at net.minecraft.crash.CrashReportCategory.func_85070_b(CrashReportCategory.java:132) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:209) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:184) ~[?:?] {re:classloading}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:598) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2053) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2014) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1368) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:489) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.crash.CrashReportCategory.func_85070_b(CrashReportCategory.java:132) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:209) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:184) ~[?:?] {re:classloading}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
-- Entity being checked for collision --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 86
	Entity Name: Tenshi
	Entity's Exact location: 2429.29, 64.58, -56.61
	Entity's Block location: World: (2429,64,-57), Chunk: (at 13,4,7 in 151,-4; contains blocks 2416,0,-64 to 2431,255,-49), Region: (4,-1; contains chunks 128,-32 to 159,-1, blocks 2048,0,-512 to 2559,255,-1)
	Entity's Momentum: 0.00, -0.23, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:598) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2053) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2014) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1368) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:489) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}


-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 86
	Entity Name: Tenshi
	Entity's Exact location: 2429.29, 64.58, -56.61
	Entity's Block location: World: (2429,64,-57), Chunk: (at 13,4,7 in 151,-4; contains blocks 2416,0,-64 to 2431,255,-49), Region: (4,-1; contains chunks 128,-32 to 159,-1, blocks 2048,0,-512 to 2559,255,-1)
	Entity's Momentum: 0.00, -0.23, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6921880240 bytes (6601 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.16.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.16
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.16-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		TesseractAPI-1.16.5-0.0.3.jar                     |TesseractAPI                  |tesseract                     |1.16.5-0.0.3        |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.16-universal.jar                |Forge                         |forge                         |36.1.16             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AntimatterAPI-1.16.5-0.0.3.jar                    |AntimatterAPI                 |antimatter                    |1.16.5-0.0.3        |DONE      |NOSIGNATURE
		GregTech-Intergalactical-1.16.5-0.0.3.jar         |GregTech Intergalactical      |gti                           |1.16.5-0.0.3        |DONE      |NOSIGNATURE
	Crash Report UUID: 761997d8-a832-4d96-8e23-bacfd6b90068
	Player Count: 1 / 8; [ServerPlayerEntity['Tenshi'/86, l='ServerLevel[Test]', x=2429.29, y=64.58, z=-56.61]]
	Data Packs: vanilla, mod:tesseract (incompatible), mod:antimatter (incompatible), mod:forge, mod:gti (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Rongmario** [comment]
End no longer crashes.
